FROM jupyter/pyspark-notebook:latest

USER root

# Установка Java и wget
RUN apt-get update && apt-get install -y wget openjdk-8-jdk

RUN pip install --no-cache-dir --upgrade --force-reinstall pyspark==3.5.0

RUN conda create -y -n spark-py38 python=3.8 pip ipykernel && \
    /opt/conda/envs/spark-py38/bin/pip install --no-cache-dir pyspark==3.5.0 && \
    /opt/conda/envs/spark-py38/bin/python -m ipykernel install \
      --prefix=/opt/conda \
      --name spark-py38 \
      --display-name "PySpark 3.5 (Python 3.8)"

# Установка Hadoop
RUN wget https://dlcdn.apache.org/hadoop/common/hadoop-3.4.1/hadoop-3.4.1.tar.gz && \
    tar -xzvf hadoop-3.4.1.tar.gz -C /opt/ && \
    mv /opt/hadoop-3.4.1 /opt/hadoop && \
    rm hadoop-3.4.1.tar.gz

# Переменные окружения для Hadoop
ENV HADOOP_HOME=/opt/hadoop
ENV PATH=$PATH:$HADOOP_HOME/bin
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV HADOOP_CONF_DIR=/etc/hadoop

ENV JUPYTER_TOKEN=fijma

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--ServerApp.token=fijma"]
