FROM jupyter/pyspark-notebook:latest

USER root

# Установка Java и wget
RUN apt-get update && apt-get install -y wget openjdk-8-jdk

# Установка Hadoop
RUN wget https://dlcdn.apache.org/hadoop/common/hadoop-3.4.1/hadoop-3.4.1.tar.gz && \
    tar -xzvf hadoop-3.4.1.tar.gz -C /opt/ && \
    mv /opt/hadoop-3.4.1 /opt/hadoop && \
    rm hadoop-3.4.1.tar.gz

# Переменные окружения для Hadoop
ENV HADOOP_HOME=/opt/hadoop
ENV PATH=$PATH:$HADOOP_HOME/bin
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV HADOOP_CONF_DIR=/etc/hadoop

ENV JUPYTER_TOKEN=fijma

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--ServerApp.token=fijma"]
